### ISSUE TITLE
el-get-install flycheck fails on Mac OSX

### ISSUE THREAD

**Issue by mstorus** [dimitri/el-get#2306]
```
el-get-version
el-get version 5.1.d596630

uname -a
Darwin my-MacBook-3.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

emacs --version
GNU Emacs 25.0.50.1

makeinfo --version
makeinfo (GNU texinfo) 4.8
```

`error in process sentinel: el-get: makeinfo el-get could not build flycheck [makeinfo -o doc/flycheck.info doc/flycheck.texi]`

```
doc/flycheck.texi:6: warning: unrecognized encoding name `UTF-8'.
doc/flycheck.texi:309: warning: @strong{Note...} produces a spurious cross-reference in Info; reword to avoid that.
doc/flycheck.texi:340: warning: @strong{Note...} produces a spurious cross-reference in Info; reword to avoid that.
doc/flycheck.texi:402: warning: @strong{Note...} produces a spurious cross-reference in Info; reword to avoid that.
doc/flycheck.texi:650: warning: @strong{Note...} produces a spurious cross-reference in Info; reword to avoid that.
doc/flycheck.texi:984: warning: @strong{Note...} produces a spurious cross-reference in Info; reword to avoid that.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:197: Unknown command `smallindentedblock'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:202: Unmatched `@end'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:213: Unknown command `smallindentedblock'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:218: Unmatched `@end'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:390: Unknown command `smallindentedblock'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:398: Unmatched `@end'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:584: Unknown command `smallindentedblock'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:589: Unmatched `@end'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:725: Unknown command `smallindentedblock'.
/Users/my_user/.emacs.d/el-get/flycheck/doc//languages.texi:730: Unmatched `@end'.
makeinfo: Removing output file `doc/flycheck.info' due to errors; use --force to preserve.
```

**Comment by mstorus** [comment]
I was able to use a workaround 

`brew install texinfo && brew link texinfo --force`

```
$ brew install texinfo
==> Downloading https://homebrew.bintray.com/bottles/texinfo-6.0.yosemite.bottle.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/texinfo-6.0.yosemite.bottle.1.tar.gz
==> Pouring texinfo-6.0.yosemite.bottle.1.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Software that uses TeX, such as lilypond and octave, require a newer version
of these files.

$ brew link texinfo --force
Linking /usr/local/Cellar/texinfo/6.0... 28 symlinks created
```

but I'm curious if there's another solution that doesn't involve overwriting links in `/usr/bin`, which may be considered a bad practice on OS X.

**Comment by npostavs** [comment]
> but I'm curious if there's another solution that doesn't involve overwriting links in /usr/bin, which may be considered a bad practice on OS X.

- You can add the original install location of `makeinfo` to `exec-path` in Emacs.
- Or you can add `(:name flycheck :build (("/wherever/makeinfo" "-o" "doc/flycheck.info" "doc/flycheck.texi")))` to your `el-get-sources`.
- Or you can avoid building the texinfo manual altogether with `(:name flycheck :build (progn nil) :info nil)`

**Comment by mstorus** [comment]
Using this workaround https://github.com/dimitri/el-get/issues/2306#issuecomment-163008164, I now run into another error.

When I try to run `flycheck-mode`, I get the following in the *Messages* buffer

```
Eager macro-expansion failure: (file-error "Cannot open load file" "no such file or directory" "let-alist") [2 times]
progn: Cannot open load file: no such file or directory, let-alist
```

**Comment by syohex** [comment]
let-alist issue was fixed at #2302. Please upgrade el-get and try again. Or upgrade Emacs because let-alist is a core package now.

**Comment by mstorus** [comment]
@syohex I ran `el-get-self-update` and tried `el-get-install flycheck` and it still fails for me with the same errors as posted originally https://github.com/dimitri/el-get/issues/2306#issue-121091269.
I already have `GNU Emacs 25.0.50.1` , is that version recent enough?

**Comment by npostavs** [comment]
What do you see when you run `M-x el-get-describe let-alist`?

**Comment by syohex** [comment]
> I already have GNU Emacs 25.0.50.1 , is that version recent enough?

If `(require 'let-alist)` does not raise error, it is enough recent version.

**Comment by mstorus** [comment]
`M-x el-get-describe let-alist`
```
let-alist is an `el-get' package.  It is built-in since Emacs 25.0.50.

Description: Easily let-bind values of an assoc-list by their names.
The package is built-in since Emacs 25.0.50.
Installed in `/Users/my_user/.emacs.d/el-get/let-alist/'.

Full definition in `/Users/my_user/.emacs.d/el-get/el-get/recipes/let-alist.rcp':
(:name let-alist
       :description "Easily let-bind values of an assoc-list by their names."
       :builtin "25.0.50"
       :type elpa
       :url "https://elpa.gnu.org/packages/let-alist.html")
```




`(require 'let-alist)`
```
File error: Cannot open load file, no such file or directory, let-alist
```

**Comment by npostavs** [comment]
Okay, so the problem is that you have an Emacs new enough that el-get *thinks* `let-alist` is builtin, but old enough so that it's actually not. Update your Emacs, or as a workaround add `(:name let-alist :builtin nil)` to your `el-get-sources`.

**Comment by mstorus** [comment]
I downgraded my emacs to `GNU Emacs 24.5.1` (this should make Emacs old enough such that el-get is not confused about the existence of `let-alist`).

Now I get an error about `seq` when I try to `M-x flycheck-mode`

```
eval-buffer: Cannot open load file: no such file or directory, seq
```

**Comment by syohex** [comment]
I cannot reproduce with Emacs 24.5.1. Could you try again after removing flycheck ?

```
(setq-default user-emacs-directory default-directory)

(add-to-list 'load-path (locate-user-emacs-file "el-get/el-get"))
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))
```

- Open above file with `emacs -Q`
- `M-x eval-buffer`
- `M-x el-get-install [RET] flycheck`

Then `seq` is installed and `M-x flycheck-mode` works well.

**Comment by npostavs** [comment]
If you have kept your `~/.emacs.d/el-get/` from before, then you may to `M-x el-get-reinstall seq`.
