### ISSUE TITLE
Cannot open load file "el-get-core"

### ISSUE THREAD

**Issue by bebekim** [dimitri/el-get#2438]
I use emacs 24.5.1 on ubuntu 16.04
and when I open up emacs, I get a message saying problem with loading el-get-core

Using `--debug-init` I get the following message: 
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "el-get-core")
  require(el-get-core)
  byte-code("\300\301!\210\300\302!\210\300\303!\207" [require cl el-get-core autoload] 2)
  load("/home/yhk/.emacs.d/elpa/el-get-5.1/el-get-autoloads" nil t)
  #[0 "\302\303\304\305\300\"\301\"\306\307#\207" [el-get "/home/yhk/.emacs.d/elpa/el-get-5.1" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"]()
  funcall(#[0 "\302\303\304\305\300\"\301\"\306\307#\207" [el-get "/home/yhk/.emacs.d/elpa/el-get-5.1" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"])
  package-activate-1([cl-struct-package-desc el-get (5 1) "Manage the external elisp bits and pieces you depend upon" nil nil nil "/home/yhk/.emacs.d/elpa/el-get-5.1" ((:keywords "emacs" "package" "elisp" "install" "elpa" "git" "git-svn" "bzr" "cvs" "svn" "darcs" "hg" "apt-get" "fink" "pacman" "http" "http-tar" "emacswiki") (:url . "http://www.emacswiki.org/emacs/el-get")) nil])
  package-activate(el-get)
  package-initialize()
  eval-buffer(#<buffer  *load*> nil "/home/yhk/.emacs.d/init.el" nil t)  ; Reading at buffer position 434
  load-with-code-conversion("/home/yhk/.emacs.d/init.el" "/home/yhk/.emacs.d/init.el" t t)
  load("/home/yhk/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

HowI don't know how to move forward from here, what do I do?

**Comment by npostavs** [comment]
How did you install el-get?

**Comment by npostavs** [comment]
> `elpa/el-get-5.1`

Oh, you installed from melpa-stable, didn't you? I think this doesn't work, because el-get was fixed to work with package.el only after 5.1 was released.

> I don't know how to move forward from here, what do I do?

Remote the `el-get` package: `M-x package-delete RET el-get-5.1 RET`
Use el-get's "lazy installer" to install it: https://github.com/dimitri/el-get#the-lazy-installer

**Comment by dadinn** [comment]
I am still experiencing the same problem.
I also use `melpa-stable`, but the current version there is `5.1.`, so I am assuming something else might cause this.

**Comment by npostavs** [comment]
Confirmed that using the following in `~/.emacs.d/init.el` (i.e., https://github.com/dimitri/el-get#alternative-basic-setup-with-installation-via-melpa with MELPA stable) gives this error. (Emacs version 27, but I guess Emacs version doesn't really matter, this is just a case of the `5.1` tag pointing to a version that doesn't handle package.el properly)

```el
(add-to-list 'load-path (expand-file-name "el-get/el-get" user-emacs-directory))

(unless (require 'el-get nil 'noerror)
  (require 'package)
  (add-to-list 'package-archives
               '("melpa-stable" . "https://stable.melpa.org/packages/"))
  (package-refresh-contents)
  (package-initialize)
  (package-install 'el-get)
  (require 'el-get))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)
```

<details>
<summary>Note to self for testing on older Emacs, use `setq` instead of `add-to-list` to avoid signature/gpg errors</summary>

```el
(add-to-list 'load-path (expand-file-name "el-get/el-get" user-emacs-directory))

(unless (require 'el-get nil 'noerror)
  (require 'package)
  (setq package-archives
        '(("melpa-stable" . "https://stable.melpa.org/packages/")))
  (package-refresh-contents)
  (package-initialize)
  (package-install 'el-get)
  (require 'el-get))

(add-to-list 'el-get-recipe-path "~/.emacs.d/el-get-user/recipes")
(el-get 'sync)
```
</details>

**Comment by npostavs** [comment]
I have tagged version 5.2 now, should be available in MELPA stable soonish (I guess within a day?)

**Comment by npostavs** [comment]
Apparently it updates every 3 hours or so. It's working now.
